on: 
  push:
    branches:
    - main

jobs:
  update-index-html:
    runs-on: ubuntu-latest
    steps:
      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc
      - name: Run bash to update index.html
        run: bash ./update-index-html.sh
